"""Add events table

Revision ID: 6f9d8f78b60f
Revises: 90e67f6f8d58
Create Date: 2025-08-02 07:25:34.800967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9d8f78b60f'
down_revision = '90e67f6f8d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=225), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('email', sa.String(length=225), nullable=False),
    sa.Column('location', sa.String(length=225), nullable=False),
    sa.Column('checked_in', sa.Boolean(), nullable=True),
    sa.Column('checked_in_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('attendees')
    # ### end Alembic commands ###
